/*
  DO NOT EDIT THIS FILE DIRECTLY.
  It is generated via `npm run update-action-refs`.
*/

/**
 * The actions we emit, pinned to the commit of their latest release at the time
 * this file was generated.
 */
export const ACTION_REFS = {
  /**
   * v7.0.1
   */
  'actions/checkout':
    'actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1',
} as const;
