import { writeFile, unlink } from 'node:fs/promises';
import { join } from 'node:path';
import { compileFromFile } from 'json-schema-to-typescript';

const SCHEMA_URL = 'https://www.schemastore.org/github-workflow.json';
const TEMP_SCHEMA_PATH = join(process.cwd(), 'github-workflow.json');
const OUTPUT_PATH = join(process.cwd(), 'src', 'github/types.ts');

async function main(): Promise<void> {
  console.log(`Fetching schema from ${SCHEMA_URL}...`);
  const response = await fetch(SCHEMA_URL);

  if (!response.ok) {
    throw new Error(
      `Failed to fetch schema: ${response.status} ${response.statusText}`,
    );
  }

  const schema = await response.text();

  console.log(`Writing schema to ${TEMP_SCHEMA_PATH}...`);
  await writeFile(TEMP_SCHEMA_PATH, schema);

  try {
    console.log('Compiling schema to TypeScript...');
    const types = await compileFromFile(TEMP_SCHEMA_PATH, {
      bannerComment: `/*
  DO NOT EDIT THIS FILE DIRECTLY.
  It is generated via \`npm run update-github-types\`.
*/`,
    });

    console.log(`Writing types to ${OUTPUT_PATH}...`);
    await writeFile(OUTPUT_PATH, types);
  } finally {
    console.log(`Removing temporary schema at ${TEMP_SCHEMA_PATH}...`);
    await unlink(TEMP_SCHEMA_PATH);
  }

  console.log('Done.');
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
