import { writeFile } from 'node:fs/promises';
import { join } from 'node:path';

/**
 * The actions we emit, whose latest releases get pinned by SHA.
 */
const ACTIONS = ['actions/checkout'];

const OUTPUT_PATH = join(process.cwd(), 'src', 'github/actions/refs.ts');

interface ActionRef {
  version: string;
  sha: string;
}

async function fetchJson(url: string): Promise<unknown> {
  const response = await fetch(url, {
    headers: {
      accept: 'application/vnd.github+json',
      'user-agent': 'tangleflow-update-action-refs',
    },
  });

  if (!response.ok) {
    throw new Error(
      `Failed to fetch ${url}: ${response.status} ${response.statusText}`,
    );
  }

  return response.json();
}

/**
 * Resolve an action's latest release to the commit it points at. Annotated tags
 * resolve to a tag object, so they need dereferencing to reach the commit.
 */
async function fetchActionRef(action: string): Promise<ActionRef> {
  const release = (await fetchJson(
    `https://api.github.com/repos/${action}/releases/latest`,
  )) as { tag_name: string };
  const version = release.tag_name;

  const ref = (await fetchJson(
    `https://api.github.com/repos/${action}/git/ref/tags/${version}`,
  )) as { object: { type: string; sha: string; url: string } };

  let { sha, type } = ref.object;

  if (type === 'tag') {
    const tag = (await fetchJson(ref.object.url)) as {
      object: { sha: string };
    };
    sha = tag.object.sha;
  }

  return { version, sha };
}

function render(refs: Record<string, ActionRef>): string {
  const entries = Object.entries(refs)
    .map(
      ([action, { version, sha }]) =>
        `  /**\n   * ${version}\n   */\n  '${action}': '${action}@${sha}'`,
    )
    .join(',\n');

  return `/*
  DO NOT EDIT THIS FILE DIRECTLY.
  It is generated via \`npm run update-action-refs\`.
*/

/**
 * The actions we emit, pinned to the commit of their latest release at the time
 * this file was generated.
 */
export const ACTION_REFS = {
${entries}
} as const;
`;
}

async function main(): Promise<void> {
  const refs = Object.fromEntries(
    await Promise.all(
      ACTIONS.map(async (action) => {
        console.log(`Resolving latest release of ${action}...`);
        const ref = await fetchActionRef(action);
        console.log(`${action} is ${ref.version} (${ref.sha})`);
        return [action, ref] as const;
      }),
    ),
  );

  console.log(`Writing refs to ${OUTPUT_PATH}...`);
  await writeFile(OUTPUT_PATH, render(refs));

  console.log('Done.');
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
